import type { Question } from "@/lib/types";

export const SEO_QUESTIONS: Record<string, Question[]> = {
  "canadian-citizenship-practice-test": [
    {
      id: "cpt-1", chapter: "general", topic: "Capital & Geography", difficulty: 1,
      source: "Discover Canada",
      question: "What is the capital city of Canada?",
      options: ["Toronto", "Ottawa", "Vancouver", "Montreal"],
      answer: 1,
      explanation: "Ottawa is the capital of Canada. It is located in the province of Ontario along the Ottawa River.",
    },
    {
      id: "cpt-2", chapter: "general", topic: "Confederation", difficulty: 1,
      source: "Discover Canada",
      question: "In which year did Canada become a country through Confederation?",
      options: ["1812", "1841", "1867", "1901"],
      answer: 2,
      explanation: "Canada became a country on July 1, 1867, when the British North America Act created the Dominion of Canada.",
    },
    {
      id: "cpt-3", chapter: "general", topic: "Official Languages", difficulty: 1,
      source: "Discover Canada",
      question: "What are the two official languages of Canada?",
      options: ["English and Spanish", "French and Indigenous languages", "English and French", "English and Inuktitut"],
      answer: 2,
      explanation: "Canada has two official languages: English and French. This is protected by the Official Languages Act of 1969.",
    },
    {
      id: "cpt-4", chapter: "general", topic: "Head of State", difficulty: 1,
      source: "Discover Canada",
      question: "Who is Canada's head of state?",
      options: ["The Prime Minister", "The Governor General", "The Monarch (King)", "The Speaker of the Senate"],
      answer: 2,
      explanation: "The Monarch (currently King Charles III) is Canada's head of state. The Governor General represents the Monarch in Canada.",
    },
    {
      id: "cpt-5", chapter: "general", topic: "Provinces & Territories", difficulty: 1,
      source: "Discover Canada",
      question: "How many provinces and territories does Canada have?",
      options: ["10 provinces and 2 territories", "9 provinces and 3 territories", "10 provinces and 3 territories", "12 provinces and 1 territory"],
      answer: 2,
      explanation: "Canada has 10 provinces and 3 territories, for a total of 13. The three territories are Yukon, Northwest Territories, and Nunavut.",
    },
  ],

  "citizenship-test-questions": [
    {
      id: "ctq-1", chapter: "rights", topic: "Charter of Rights", difficulty: 1,
      source: "Discover Canada",
      question: "What is the Canadian Charter of Rights and Freedoms?",
      options: ["A federal election law", "Part of the Constitution Act, 1982", "A Supreme Court ruling from 1960", "A provincial human rights code"],
      answer: 1,
      explanation: "The Canadian Charter of Rights and Freedoms is part of the Constitution Act, 1982. It guarantees the rights and freedoms of all Canadians.",
    },
    {
      id: "ctq-2", chapter: "rights", topic: "Voting Rights", difficulty: 1,
      source: "Discover Canada",
      question: "Who has the right to vote in Canadian federal elections?",
      options: ["All residents of Canada", "Canadian citizens aged 18 and older", "Canadian citizens aged 16 and older", "All adults with a valid work permit"],
      answer: 1,
      explanation: "Canadian citizens who are 18 years of age or older on election day have the right to vote in federal elections.",
    },
    {
      id: "ctq-3", chapter: "rights", topic: "Responsibilities", difficulty: 1,
      source: "Discover Canada",
      question: "Which of the following is a responsibility of Canadian citizenship?",
      options: ["Registering with a political party", "Obeying the law and serving on jury duty", "Paying taxes only if earning over $50,000", "Learning only English"],
      answer: 1,
      explanation: "Obeying the law, serving on jury duty when called, and paying taxes are among the key responsibilities of Canadian citizens.",
    },
    {
      id: "ctq-4", chapter: "rights", topic: "Equality Rights", difficulty: 2,
      source: "Discover Canada",
      question: "Under the Canadian Charter, which section guarantees equality rights?",
      options: ["Section 2", "Section 7", "Section 15", "Section 33"],
      answer: 2,
      explanation: "Section 15 of the Charter guarantees every individual is equal before and under the law without discrimination based on race, national or ethnic origin, sex, age, or disability.",
    },
    {
      id: "ctq-5", chapter: "rights", topic: "Fundamental Freedoms", difficulty: 1,
      source: "Discover Canada",
      question: "Which freedom is NOT listed under fundamental freedoms in the Charter?",
      options: ["Freedom of speech and expression", "Freedom of religion", "Freedom to own property", "Freedom of peaceful assembly"],
      answer: 2,
      explanation: "The Charter's fundamental freedoms include conscience, religion, expression, peaceful assembly, and association — but not property rights.",
    },
  ],

  "discover-canada-practice-test": [
    {
      id: "dcp-1", chapter: "history", topic: "First Nations", difficulty: 1,
      source: "Discover Canada",
      question: "Who are the Aboriginal peoples of Canada?",
      options: ["French and British settlers", "First Nations, Métis, and Inuit", "Indigenous and French Canadians", "Early European explorers"],
      answer: 1,
      explanation: "The Aboriginal peoples of Canada are the First Nations, Métis, and Inuit. They are the original inhabitants of Canada.",
    },
    {
      id: "dcp-2", chapter: "history", topic: "Explorers", difficulty: 2,
      source: "Discover Canada",
      question: "Which explorer is credited with claiming Canada for France in 1534?",
      options: ["Samuel de Champlain", "John Cabot", "Jacques Cartier", "Henry Hudson"],
      answer: 2,
      explanation: "Jacques Cartier sailed to Canada in 1534 and claimed it for France. He is often called the father of Canada.",
    },
    {
      id: "dcp-3", chapter: "history", topic: "War of 1812", difficulty: 2,
      source: "Discover Canada",
      question: "The War of 1812 was fought between Canada (with Britain) and which country?",
      options: ["France", "The United States", "Spain", "Russia"],
      answer: 1,
      explanation: "The War of 1812 was fought between the United States and British forces including Canadian militias. The war helped forge a distinct Canadian identity.",
    },
    {
      id: "dcp-4", chapter: "history", topic: "Confederation Fathers", difficulty: 2,
      source: "Discover Canada",
      question: "Who is often called the 'Father of Confederation' and Canada's first Prime Minister?",
      options: ["Wilfrid Laurier", "George-Étienne Cartier", "John A. Macdonald", "Charles Tupper"],
      answer: 2,
      explanation: "Sir John A. Macdonald was a leading Father of Confederation and became Canada's first Prime Minister in 1867.",
    },
    {
      id: "dcp-5", chapter: "history", topic: "National Symbols", difficulty: 1,
      source: "Discover Canada",
      question: "What does the maple leaf on Canada's flag represent?",
      options: ["The forests of Canada", "National unity and identity", "The two official languages", "The French heritage"],
      answer: 1,
      explanation: "The maple leaf has been a symbol of Canada since the 1700s. Canada's red-and-white flag featuring the maple leaf was adopted in 1965.",
    },
  ],

  "free-citizenship-test": [
    {
      id: "fct-1", chapter: "government", topic: "System of Government", difficulty: 1,
      source: "Discover Canada",
      question: "What type of government does Canada have?",
      options: ["Presidential republic", "Constitutional monarchy with parliamentary democracy", "Absolute monarchy", "Federal republic"],
      answer: 1,
      explanation: "Canada is a constitutional monarchy with a parliamentary democracy. The Monarch is head of state, but elected representatives govern the country.",
    },
    {
      id: "fct-2", chapter: "government", topic: "Parliament", difficulty: 1,
      source: "Discover Canada",
      question: "What are the three parts of Canada's Parliament?",
      options: ["The Prime Minister, the Cabinet, and the Senate", "The Crown, the Senate, and the House of Commons", "The Governor General, the House of Commons, and the Courts", "The Senate, the House of Commons, and the Supreme Court"],
      answer: 1,
      explanation: "Canada's Parliament consists of three parts: the Crown (Monarch/Governor General), the Senate (appointed upper house), and the House of Commons (elected lower house).",
    },
    {
      id: "fct-3", chapter: "government", topic: "Federal Elections", difficulty: 1,
      source: "Discover Canada",
      question: "How often must a federal election be held in Canada?",
      options: ["Every 3 years", "Every 4 years (at least)", "Every 5 years (at least)", "Every 6 years"],
      answer: 2,
      explanation: "Under the Constitution, a federal election must be held at least every 5 years. Fixed election dates are set for every 4 years unless Parliament is dissolved earlier.",
    },
    {
      id: "fct-4", chapter: "government", topic: "Prime Minister", difficulty: 1,
      source: "Discover Canada",
      question: "How does Canada's Prime Minister come to power?",
      options: ["Appointed by the Governor General for 5 years", "Elected directly by Canadians in a separate vote", "Leader of the party with the most seats in the House of Commons", "Chosen by the Senate"],
      answer: 2,
      explanation: "The Prime Minister is the leader of the political party that wins the most seats in the House of Commons in a federal election.",
    },
    {
      id: "fct-5", chapter: "government", topic: "Senate", difficulty: 2,
      source: "Discover Canada",
      question: "How many senators are there in Canada's Senate?",
      options: ["69", "85", "105", "308"],
      answer: 2,
      explanation: "Canada's Senate has 105 seats. Senators are appointed by the Governor General on the advice of the Prime Minister and serve until age 75.",
    },
  ],

  "citizenship-test-ontario": [
    {
      id: "cto-1", chapter: "ontario", topic: "Ontario Facts", difficulty: 1,
      source: "Discover Canada",
      question: "What is the capital city of Ontario?",
      options: ["Ottawa", "Hamilton", "Toronto", "Kingston"],
      answer: 2,
      explanation: "Toronto is the capital of Ontario and is also Canada's largest city with a population of over 2.7 million people.",
    },
    {
      id: "cto-2", chapter: "ontario", topic: "Ontario History", difficulty: 2,
      source: "Discover Canada",
      question: "Ontario is known as Canada's most populous province. Approximately how many people live there?",
      options: ["About 5 million", "About 10 million", "About 14 million", "About 20 million"],
      answer: 2,
      explanation: "Ontario has a population of approximately 14–15 million people, making it the most populous province and home to about 38% of all Canadians.",
    },
    {
      id: "cto-3", chapter: "ontario", topic: "Great Lakes", difficulty: 1,
      source: "Discover Canada",
      question: "Which Great Lakes border Ontario?",
      options: ["Superior, Michigan, and Erie only", "Huron, Erie, and Ontario only", "Superior, Huron, Erie, and Ontario", "All five Great Lakes"],
      answer: 2,
      explanation: "Ontario borders four of the five Great Lakes: Lake Superior, Lake Huron, Lake Erie, and Lake Ontario. Lake Michigan is entirely within the United States.",
    },
    {
      id: "cto-4", chapter: "ontario", topic: "Provincial Government", difficulty: 1,
      source: "Discover Canada",
      question: "What is the provincial legislature of Ontario called?",
      options: ["The Ontario Senate", "The Legislative Assembly of Ontario", "The Ontario Parliament Buildings", "The Ontario House of Commons"],
      answer: 1,
      explanation: "Ontario's provincial legislature is called the Legislative Assembly of Ontario. It is located at Queen's Park in Toronto.",
    },
    {
      id: "cto-5", chapter: "ontario", topic: "Canadian History", difficulty: 2,
      source: "Discover Canada",
      question: "What was Ontario called before Confederation in 1867?",
      options: ["New France", "Upper Canada", "Nova Scotia", "Rupert's Land"],
      answer: 1,
      explanation: "Ontario was called Upper Canada from 1791. After the Act of Union in 1841, it became Canada West, and after Confederation in 1867, it became the province of Ontario.",
    },
  ],

  "citizenship-test-toronto": [
    {
      id: "ctt-1", chapter: "toronto", topic: "Toronto Facts", difficulty: 1,
      source: "Discover Canada",
      question: "Toronto is Canada's largest city. What is its approximate population?",
      options: ["About 1 million", "About 2.7 million in the city proper", "About 5 million in the city", "About 8 million"],
      answer: 1,
      explanation: "Toronto has a population of approximately 2.7 million in the city proper. The Greater Toronto Area (GTA) has over 6 million people, making it the 4th largest city in North America.",
    },
    {
      id: "ctt-2", chapter: "toronto", topic: "Toronto History", difficulty: 2,
      source: "Discover Canada",
      question: "What was Toronto called before it was renamed in 1834?",
      options: ["Muddy York", "Fort Rouillé", "New France", "York"],
      answer: 3,
      explanation: "Toronto was called 'York' from 1793. It was nicknamed 'Muddy York' by residents but was officially renamed Toronto in 1834 when it was incorporated as a city.",
    },
    {
      id: "ctt-3", chapter: "toronto", topic: "National Landmarks", difficulty: 1,
      source: "Discover Canada",
      question: "Which famous tower is located in Toronto?",
      options: ["The Peace Tower", "The CN Tower", "The Olympic Tower", "Niagara Tower"],
      answer: 1,
      explanation: "The CN Tower is one of Toronto's most iconic landmarks. It stands 553.3 metres tall and was the world's tallest free-standing structure from 1976 to 2007.",
    },
    {
      id: "ctt-4", chapter: "toronto", topic: "Multiculturalism", difficulty: 1,
      source: "Discover Canada",
      question: "Canada's Multiculturalism Act recognizes the diversity of Canadians. When was it passed?",
      options: ["1969", "1982", "1988", "1995"],
      answer: 2,
      explanation: "The Canadian Multiculturalism Act was passed in 1988. It affirms Canada's multicultural heritage and promotes the full and equitable participation of all Canadians.",
    },
    {
      id: "ctt-5", chapter: "toronto", topic: "Canadian Values", difficulty: 1,
      source: "Discover Canada",
      question: "Which statement best describes Canadian values?",
      options: ["Canada values only English and French cultures", "Canada believes in equality, respect for cultural differences, and the rule of law", "Canada requires all immigrants to abandon their cultural heritage", "Canada only welcomes immigrants from Commonwealth countries"],
      answer: 1,
      explanation: "Canada is a diverse society that values equality, respect for all cultural backgrounds, peaceful coexistence, and the rule of law. These are core Canadian values.",
    },
  ],

  "canadian-citizenship-test": [
    {
      id: "cct-1", chapter: "general", topic: "Physical Presence", difficulty: 2,
      source: "Discover Canada",
      question: "How many days of physical presence in Canada are required to apply for citizenship?",
      options: ["730 days in 5 years", "1095 days in 5 years", "1460 days in 5 years", "2 years continuously"],
      answer: 1,
      explanation: "Applicants must be physically present in Canada for at least 1,095 days (3 years) within the 5 years before applying.",
    },
    {
      id: "cct-2", chapter: "general", topic: "Study Guide", difficulty: 1,
      source: "Discover Canada",
      question: "What is the official study guide for the Canadian citizenship test?",
      options: ["Welcome to Canada", "My Canada", "Discover Canada", "The Citizenship Handbook"],
      answer: 2,
      explanation: "Discover Canada: The Rights and Responsibilities of Citizenship is the official IRCC study guide used for the citizenship test.",
    },
    {
      id: "cct-3", chapter: "government", topic: "Governor General", difficulty: 2,
      source: "Discover Canada",
      question: "What is the primary role of Canada's Governor General?",
      options: ["To lead the federal government", "To represent the Monarch and perform constitutional duties", "To command the military", "To appoint the Prime Minister independently"],
      answer: 1,
      explanation: "The Governor General represents the Monarch in Canada and performs constitutional duties such as granting Royal Assent and swearing in the PM.",
    },
    {
      id: "cct-4", chapter: "rights", topic: "Charter of Rights", difficulty: 2,
      source: "Discover Canada",
      question: "In what year was the Canadian Charter of Rights and Freedoms added to the Constitution?",
      options: ["1960", "1971", "1982", "1988"],
      answer: 2,
      explanation: "The Charter became part of the Constitution Act, 1982, when Canada patriated its Constitution from the UK.",
    },
    {
      id: "cct-5", chapter: "government", topic: "Governor General Appointment", difficulty: 2,
      source: "Discover Canada",
      question: "Who formally appoints Canada's Governor General?",
      options: ["The Prime Minister", "The Monarch on the advice of the Prime Minister", "The Senate", "The Supreme Court Chief Justice"],
      answer: 1,
      explanation: "The Monarch appoints the Governor General on the advice of the Prime Minister of Canada.",
    },
  ],

  "canadian-citizenship-test-practice": [
    {
      id: "cctp-1", chapter: "general", topic: "National Anthem", difficulty: 1,
      source: "Discover Canada",
      question: "What is Canada's national anthem?",
      options: ["God Save the King", "The Maple Leaf Forever", "O Canada", "True North Strong"],
      answer: 2,
      explanation: "O Canada is Canada's national anthem. It was officially proclaimed on July 1, 1980.",
    },
    {
      id: "cctp-2", chapter: "government", topic: "House of Commons", difficulty: 1,
      source: "Discover Canada",
      question: "How many seats are in Canada's House of Commons?",
      options: ["105", "265", "338", "400"],
      answer: 2,
      explanation: "The House of Commons has 338 seats. Each seat represents an electoral district (riding) across Canada.",
    },
    {
      id: "cctp-3", chapter: "government", topic: "Supreme Court", difficulty: 1,
      source: "Discover Canada",
      question: "What is the highest court in Canada?",
      options: ["The Federal Court", "The Court of Appeal", "The Supreme Court of Canada", "The Court of Queen's Bench"],
      answer: 2,
      explanation: "The Supreme Court of Canada is the country's highest court and final court of appeal, interpreting the Constitution.",
    },
    {
      id: "cctp-4", chapter: "general", topic: "Remembrance Day", difficulty: 1,
      source: "Discover Canada",
      question: "On what date is Remembrance Day observed in Canada?",
      options: ["October 11", "November 11", "December 11", "January 11"],
      answer: 1,
      explanation: "Remembrance Day is observed on November 11 each year to honour Canadians who died in military service, especially WWI and WWII.",
    },
    {
      id: "cctp-5", chapter: "general", topic: "Medicare", difficulty: 1,
      source: "Discover Canada",
      question: "What is the name of Canada's publicly funded health care system?",
      options: ["HealthCare Canada", "Universal Health Fund", "Medicare", "Canadian Medical Insurance"],
      answer: 2,
      explanation: "Canada's publicly funded health care system is commonly called Medicare. It is governed by the Canada Health Act of 1984.",
    },
  ],

  "canadian-citizenship-test-questions-and-answers": [
    {
      id: "cctqa-1", chapter: "history", topic: "Confederation", difficulty: 1,
      source: "Discover Canada",
      question: "Which Act formally created Canada as a country in 1867?",
      options: ["The Canada Act", "The British North America Act", "The Confederation Treaty", "The Dominion Act"],
      answer: 1,
      explanation: "The British North America Act, 1867 (now called the Constitution Act, 1867) united three colonies into the Dominion of Canada.",
    },
    {
      id: "cctqa-2", chapter: "rights", topic: "Notwithstanding Clause", difficulty: 3,
      source: "Discover Canada",
      question: "What does Section 33 of the Charter — the 'notwithstanding clause' — allow?",
      options: ["Parliament to suspend elections", "Provinces to override certain Charter rights temporarily", "The Senate to block any bill", "Citizens to petition the Monarch"],
      answer: 1,
      explanation: "Section 33 (the notwithstanding clause) allows Parliament or a provincial legislature to override certain Charter rights for a renewable 5-year period.",
    },
    {
      id: "cctqa-3", chapter: "general", topic: "IRCC", difficulty: 1,
      source: "Discover Canada",
      question: "What does the acronym IRCC stand for?",
      options: ["International Refugee and Citizenship Commission", "Immigration, Refugees and Citizenship Canada", "Immigration Regulations and Consular Council", "Independent Review of Canadian Citizenship"],
      answer: 1,
      explanation: "IRCC stands for Immigration, Refugees and Citizenship Canada — the federal department that manages immigration and citizenship applications.",
    },
    {
      id: "cctqa-4", chapter: "history", topic: "Fathers of Confederation", difficulty: 1,
      source: "Discover Canada",
      question: "Who were the Fathers of Confederation?",
      options: ["The first MPs elected in 1867", "Leaders who united the British colonies to create Canada in 1867", "The original premiers of all provinces", "Explorers who first mapped Canada"],
      answer: 1,
      explanation: "The Fathers of Confederation were the political leaders from the British North American colonies who negotiated and created Canada in 1867.",
    },
    {
      id: "cctqa-5", chapter: "government", topic: "Senate Role", difficulty: 2,
      source: "Discover Canada",
      question: "What is the primary role of the Senate in Parliament?",
      options: ["To introduce money bills", "To review, revise, and pass legislation from the House of Commons", "To appoint judges", "To represent provincial governments federally"],
      answer: 1,
      explanation: "The Senate is Parliament's upper chamber. It reviews and revises legislation passed by the House of Commons, providing a 'sober second thought.'",
    },
  ],

  "canadian-citizenship-test-mock-exam": [
    {
      id: "cctme-1", chapter: "general", topic: "Test Format", difficulty: 1,
      source: "Discover Canada",
      question: "How many questions are on the Canadian citizenship test?",
      options: ["15", "18", "20", "25"],
      answer: 2,
      explanation: "The Canadian citizenship test consists of 20 multiple-choice questions based on the Discover Canada guide.",
    },
    {
      id: "cctme-2", chapter: "general", topic: "Passing Score", difficulty: 1,
      source: "Discover Canada",
      question: "What is the passing score on the citizenship test?",
      options: ["50% (10/20)", "60% (12/20)", "75% (15/20)", "80% (16/20)"],
      answer: 2,
      explanation: "You must answer at least 15 of the 20 questions correctly (75%) to pass the citizenship test.",
    },
    {
      id: "cctme-3", chapter: "general", topic: "Test Age Requirement", difficulty: 1,
      source: "Discover Canada",
      question: "Which age group is required to take the written citizenship test?",
      options: ["All applicants", "Ages 14–54", "Ages 18–54", "Ages 18–64"],
      answer: 2,
      explanation: "Applicants between 18 and 54 years of age must take the written citizenship test. Those outside this range are exempt.",
    },
    {
      id: "cctme-4", chapter: "general", topic: "Test Duration", difficulty: 1,
      source: "Discover Canada",
      question: "How long do applicants have to complete the citizenship test?",
      options: ["20 minutes", "30 minutes", "45 minutes", "1 hour"],
      answer: 2,
      explanation: "Applicants are given 45 minutes to complete the 20-question citizenship test.",
    },
    {
      id: "cctme-5", chapter: "general", topic: "Test Failure", difficulty: 2,
      source: "Discover Canada",
      question: "What happens if an applicant fails the citizenship test?",
      options: ["They must wait 2 years to reapply", "They are automatically deported", "They can be invited to a hearing or given a second written test", "They must restart the entire PR process"],
      answer: 2,
      explanation: "If you fail the written test, IRCC may invite you to a hearing before a citizenship judge, or allow you to rewrite the test.",
    },
  ],

  "discover-canada-summary": [
    {
      id: "dcs-1", chapter: "history", topic: "Aboriginal Peoples", difficulty: 1,
      source: "Discover Canada",
      question: "What are the three groups of Aboriginal peoples in Canada recognized by the Constitution?",
      options: ["Algonquin, Iroquois, and Cree", "First Nations, Métis, and Inuit", "Native, Indigenous, and Traditional", "Status Indian, Non-Status Indian, and Inuit"],
      answer: 1,
      explanation: "The Constitution of Canada recognizes three groups of Aboriginal peoples: First Nations, Métis, and Inuit — each with a distinct heritage and culture.",
    },
    {
      id: "dcs-2", chapter: "history", topic: "First Prime Minister", difficulty: 1,
      source: "Discover Canada",
      question: "Who was Canada's first Prime Minister after Confederation in 1867?",
      options: ["Wilfrid Laurier", "George-Étienne Cartier", "John A. Macdonald", "Charles Tupper"],
      answer: 2,
      explanation: "Sir John A. Macdonald was Canada's first Prime Minister. He served from 1867 to 1873 and again from 1878 to 1891.",
    },
    {
      id: "dcs-3", chapter: "history", topic: "Vimy Ridge", difficulty: 2,
      source: "Discover Canada",
      question: "In what year did Canadian forces capture Vimy Ridge in World War I?",
      options: ["1914", "1916", "1917", "1918"],
      answer: 2,
      explanation: "Canadian forces captured Vimy Ridge on April 9–12, 1917. It was a defining moment in Canadian national identity and military history.",
    },
    {
      id: "dcs-4", chapter: "general", topic: "National Animal", difficulty: 1,
      source: "Discover Canada",
      question: "What is Canada's national animal?",
      options: ["Moose", "Loon", "Beaver", "Canada Goose"],
      answer: 2,
      explanation: "The beaver is Canada's national animal. It has been a symbol of Canada since the fur trade era and appears on the five-cent coin.",
    },
    {
      id: "dcs-5", chapter: "general", topic: "Citizenship Ceremony", difficulty: 2,
      source: "Discover Canada",
      question: "Who presides over the Canadian citizenship ceremony?",
      options: ["The Prime Minister", "A citizenship judge or commissioner", "The Governor General personally", "The local MP"],
      answer: 1,
      explanation: "Citizenship ceremonies are presided over by a citizenship judge or commissioner appointed by IRCC. Sometimes the Governor General attends special ceremonies.",
    },
  ],

  "discover-canada-important-questions": [
    {
      id: "dciq-1", chapter: "general", topic: "Canada Day", difficulty: 1,
      source: "Discover Canada",
      question: "What does Canada Day celebrate and when is it?",
      options: ["Victory in WWII, May 8", "Canadian Confederation in 1867, July 1", "The Charter of Rights, April 17", "The national flag adoption, February 15"],
      answer: 1,
      explanation: "Canada Day is celebrated on July 1 and marks the anniversary of Confederation — when Canada became a country on July 1, 1867.",
    },
    {
      id: "dciq-2", chapter: "government", topic: "Senate Seats", difficulty: 1,
      source: "Discover Canada",
      question: "How many seats are in the Canadian Senate?",
      options: ["69", "85", "105", "308"],
      answer: 2,
      explanation: "Canada's Senate has 105 seats. Senators are appointed by the Monarch on the advice of the Prime Minister and serve until age 75.",
    },
    {
      id: "dciq-3", chapter: "general", topic: "Oath of Citizenship", difficulty: 1,
      source: "Discover Canada",
      question: "What is the Oath of Citizenship?",
      options: ["A written exam about Canadian history", "A solemn promise of loyalty to Canada and its laws made at the citizenship ceremony", "A contract signed with IRCC when applying for citizenship", "A pledge made when arriving as a permanent resident"],
      answer: 1,
      explanation: "The Oath of Citizenship is taken at the citizenship ceremony. By taking it, new citizens pledge allegiance to the Monarch and promise to follow Canadian laws.",
    },
    {
      id: "dciq-4", chapter: "general", topic: "Official Languages", difficulty: 1,
      source: "Discover Canada",
      question: "What are Canada's two official languages?",
      options: ["English and Spanish", "English and French", "French and Inuktitut", "English and Indigenous languages"],
      answer: 1,
      explanation: "Canada has two official languages: English and French. This is enshrined in the Constitution Act, 1982 and the Official Languages Act of 1969.",
    },
    {
      id: "dciq-5", chapter: "government", topic: "Head of Government", difficulty: 1,
      source: "Discover Canada",
      question: "Who is Canada's head of government?",
      options: ["The Governor General", "The Monarch", "The Prime Minister", "The Chief Justice of the Supreme Court"],
      answer: 2,
      explanation: "The Prime Minister is Canada's head of government. The head of state is the Monarch, represented in Canada by the Governor General.",
    },
  ],

  "how-to-pass-canadian-citizenship-test": [
    {
      id: "htpct-1", chapter: "government", topic: "Head of State vs Government", difficulty: 2,
      source: "Discover Canada",
      question: "A common mistake on the citizenship test is confusing who is Canada's head of STATE vs head of GOVERNMENT. Who is the head of STATE?",
      options: ["The Prime Minister", "The Speaker of the House", "The Monarch (King/Queen)", "The Governor General"],
      answer: 2,
      explanation: "The Monarch (King Charles III) is Canada's head of STATE. The Governor General represents the Monarch. The Prime Minister is the head of GOVERNMENT.",
    },
    {
      id: "htpct-2", chapter: "general", topic: "Study Guide", difficulty: 1,
      source: "Discover Canada",
      question: "Which official study guide should you use to prepare for the Canadian citizenship test?",
      options: ["Welcome to Canada", "Know Your Rights", "Discover Canada: The Rights and Responsibilities of Citizenship", "The Immigrant's Guide to Canada"],
      answer: 2,
      explanation: "The official study guide is Discover Canada: The Rights and Responsibilities of Citizenship, published by IRCC. All test questions come from this guide.",
    },
    {
      id: "htpct-3", chapter: "general", topic: "Passing Score", difficulty: 1,
      source: "Discover Canada",
      question: "How many questions can you get wrong and still pass the citizenship test?",
      options: ["0 — you must get all 20 correct", "3 or fewer", "5 or fewer", "8 or fewer"],
      answer: 2,
      explanation: "The passing score is 75% (15/20). You can get up to 5 questions wrong and still pass the test.",
    },
    {
      id: "htpct-4", chapter: "general", topic: "Study Priority", difficulty: 2,
      source: "Discover Canada",
      question: "Which section of Discover Canada covers the most heavily tested material?",
      options: ["Canada's Geography", "Rights and Responsibilities of Citizenship", "Canadian Symbols", "Immigration History"],
      answer: 1,
      explanation: "The Rights and Responsibilities section and the Government chapters are most heavily represented on the citizenship test. Focus on these areas first.",
    },
    {
      id: "htpct-5", chapter: "general", topic: "Test Strategy", difficulty: 1,
      source: "Discover Canada",
      question: "What is the best strategy for questions you are unsure about?",
      options: ["Skip them entirely", "Always choose the longest answer", "Use elimination — remove obviously wrong answers first", "Guess option A"],
      answer: 2,
      explanation: "The best strategy is process of elimination: rule out clearly wrong answers first, then choose from the remaining options. This significantly improves your odds.",
    },
  ],

  "how-hard-is-the-canadian-citizenship-test": [
    {
      id: "hhcct-1", chapter: "rights", topic: "Equality Rights", difficulty: 3,
      source: "Discover Canada",
      question: "(Hard) Section 15 of the Canadian Charter of Rights and Freedoms guarantees what?",
      options: ["Freedom of religion", "The right to vote", "Equality rights — protection from discrimination", "Legal rights including the right to a lawyer"],
      answer: 2,
      explanation: "Section 15 is the Equality Rights section. It guarantees every individual is equal before the law without discrimination based on race, sex, age, disability, and more.",
    },
    {
      id: "hhcct-2", chapter: "government", topic: "Prime Minister", difficulty: 2,
      source: "Discover Canada",
      question: "(Medium) How does a person become Canada's Prime Minister?",
      options: ["Directly elected by all Canadians in a national vote", "Appointed by the Governor General for a 4-year term", "As leader of the party winning the most House of Commons seats", "Chosen by the Senate"],
      answer: 2,
      explanation: "The Prime Minister is the leader of the political party that wins the most seats in the House of Commons in a federal election.",
    },
    {
      id: "hhcct-3", chapter: "general", topic: "Capital City", difficulty: 1,
      source: "Discover Canada",
      question: "(Easy) What is the capital of Canada?",
      options: ["Toronto", "Montreal", "Vancouver", "Ottawa"],
      answer: 3,
      explanation: "Ottawa is the capital of Canada. It is located in the province of Ontario on the Ottawa River, bordering Quebec.",
    },
    {
      id: "hhcct-4", chapter: "rights", topic: "Habeas Corpus", difficulty: 3,
      source: "Discover Canada",
      question: "(Hard) What is habeas corpus?",
      options: ["A law requiring citizens to pay taxes", "The right of a detained person to require a court to rule on the lawfulness of their detention", "The oath taken by new citizens", "A Senate procedural rule"],
      answer: 1,
      explanation: "Habeas corpus is an ancient legal principle that requires authorities to justify detaining a person before a court. It is a fundamental protection of individual liberty in Canada.",
    },
    {
      id: "hhcct-5", chapter: "general", topic: "Provinces", difficulty: 1,
      source: "Discover Canada",
      question: "(Medium) How many provinces does Canada have?",
      options: ["8", "9", "10", "12"],
      answer: 2,
      explanation: "Canada has 10 provinces: Ontario, Quebec, British Columbia, Alberta, Saskatchewan, Manitoba, Nova Scotia, New Brunswick, PEI, and Newfoundland and Labrador.",
    },
  ],

  "canadian-citizenship-eligibility": [
    {
      id: "cce-1", chapter: "general", topic: "Minimum Age", difficulty: 1,
      source: "Discover Canada",
      question: "What is the minimum age to independently apply for Canadian citizenship?",
      options: ["16", "18", "21", "No minimum age"],
      answer: 1,
      explanation: "Applicants must be at least 18 years old to apply independently for citizenship. Minor children can be included in a parent's application.",
    },
    {
      id: "cce-2", chapter: "general", topic: "Tax Filing Requirement", difficulty: 2,
      source: "Discover Canada",
      question: "How many years of income tax returns must an eligible applicant have filed?",
      options: ["1 of the last 3 years", "3 of the last 5 years", "5 of the last 10 years", "Every year since becoming a PR"],
      answer: 1,
      explanation: "Citizenship applicants must have filed income taxes for at least 3 of the last 5 tax years to demonstrate compliance with Canadian tax obligations.",
    },
    {
      id: "cce-3", chapter: "general", topic: "Physical Presence", difficulty: 2,
      source: "Discover Canada",
      question: "How many days of physical presence in Canada are required in the 5 years before applying for citizenship?",
      options: ["730 days", "1000 days", "1095 days", "1460 days"],
      answer: 2,
      explanation: "Applicants must have been physically present in Canada for at least 1,095 days (approximately 3 years) within the 5 years before applying.",
    },
    {
      id: "cce-4", chapter: "general", topic: "Criminal Prohibition", difficulty: 2,
      source: "Discover Canada",
      question: "An applicant convicted of an indictable offence in Canada is prohibited from applying for citizenship for how long?",
      options: ["1 year", "2 years", "4 years from the date of conviction", "Permanently"],
      answer: 2,
      explanation: "A person convicted of an indictable offence in Canada cannot apply for citizenship for 4 years from the date of conviction. Criminal history is carefully reviewed.",
    },
    {
      id: "cce-5", chapter: "general", topic: "Language Requirement", difficulty: 2,
      source: "Discover Canada",
      question: "What language proficiency level is required for citizenship applicants aged 18–54?",
      options: ["CLB 2 (basic)", "CLB 4 (basic conversational)", "CLB 7 (intermediate)", "CLB 10 (advanced)"],
      answer: 1,
      explanation: "Citizenship applicants aged 18–54 must demonstrate adequate knowledge of English or French at a minimum of CLB (Canadian Language Benchmark) level 4.",
    },
  ],

  "canadian-citizenship-calculator": [
    {
      id: "ccc-1", chapter: "general", topic: "Physical Presence Requirement", difficulty: 1,
      source: "Discover Canada",
      question: "How many days of physical presence are required in Canada to qualify for citizenship?",
      options: ["730 days in 3 years", "1095 days in 5 years", "1460 days in 5 years", "900 days in 3 years"],
      answer: 1,
      explanation: "You must be physically present in Canada for at least 1,095 days within the 5-year period immediately before your application date.",
    },
    {
      id: "ccc-2", chapter: "general", topic: "Temporary Resident Days", difficulty: 2,
      source: "Discover Canada",
      question: "Before becoming a permanent resident, do days spent in Canada as a temporary resident count toward the citizenship physical presence requirement?",
      options: ["No, only days as a PR count", "Yes, fully — one day as a temporary resident counts as one day", "Yes, at half credit — up to 365 days maximum", "Yes, but only if on a work or study permit"],
      answer: 2,
      explanation: "Days spent in Canada as a temporary resident (work/study permit or visitor) before becoming a PR count at half credit, up to a maximum of 365 days.",
    },
    {
      id: "ccc-3", chapter: "general", topic: "Calculation Window", difficulty: 2,
      source: "Discover Canada",
      question: "The 5-year calculation window for the physical presence requirement ends on what date?",
      options: ["The date of your citizenship ceremony", "The date IRCC approves your application", "The date you sign your citizenship application", "Today's date when you are checking"],
      answer: 2,
      explanation: "The physical presence calculation looks at the 5 years before the date you sign your citizenship application.",
    },
    {
      id: "ccc-4", chapter: "general", topic: "Days Outside Canada", difficulty: 1,
      source: "Discover Canada",
      question: "Do days spent outside Canada count toward the physical presence requirement?",
      options: ["Yes, if for work purposes", "Yes, if travelling with a Canadian spouse", "No — only days physically in Canada count", "Yes, up to 60 days per year"],
      answer: 2,
      explanation: "Only days you are physically present inside Canada count toward the requirement. Days outside Canada — for any reason — do not count.",
    },
    {
      id: "ccc-5", chapter: "general", topic: "PR Residency Obligation", difficulty: 2,
      source: "Discover Canada",
      question: "For permanent residents, what is the residency obligation to maintain PR status?",
      options: ["Must be in Canada every day", "730 days in a 5-year period", "1095 days in a 5-year period", "365 days per year"],
      answer: 1,
      explanation: "Permanent residents must be physically present in Canada for at least 730 days in every 5-year period to maintain their PR status — different from the 1,095 days needed for citizenship.",
    },
  ],

  "canadian-citizenship-interview-questions": [
    {
      id: "cciq-1", chapter: "general", topic: "Documents to Bring", difficulty: 1,
      source: "Discover Canada",
      question: "What documents should you typically bring to a citizenship interview or test appointment?",
      options: ["Only your passport", "Your Notice to Appear, passport, PR card, and supporting documents for your physical presence", "Just your IRCC application number", "Your birth certificate and provincial health card only"],
      answer: 1,
      explanation: "You should bring your Notice to Appear, passport, PR card (or other travel documents), and any documents supporting your physical presence calculation (travel records, pay stubs, etc.).",
    },
    {
      id: "cciq-2", chapter: "general", topic: "Travel History Questions", difficulty: 2,
      source: "Discover Canada",
      question: "Why does the citizenship officer ask detailed questions about your travel history?",
      options: ["To check if you have a valid travel visa", "To verify that you have met the 1,095-day physical presence requirement", "To confirm your dual citizenship status", "To assess your language skills"],
      answer: 1,
      explanation: "Travel history questions are used to verify your physical presence in Canada. The officer cross-references your travel records to confirm you have met the 1,095-day requirement.",
    },
    {
      id: "cciq-3", chapter: "general", topic: "Language CLB Level", difficulty: 2,
      source: "Discover Canada",
      question: "What is the minimum language proficiency level (CLB) required for citizenship applicants aged 18–54?",
      options: ["CLB 2", "CLB 4", "CLB 6", "CLB 8"],
      answer: 1,
      explanation: "CLB (Canadian Language Benchmark) level 4 is the minimum language proficiency required in English or French for citizenship applicants between 18 and 54 years old.",
    },
    {
      id: "cciq-4", chapter: "general", topic: "Physical Presence Definition", difficulty: 2,
      source: "Discover Canada",
      question: "When calculating physical presence, what counts as being 'in Canada'?",
      options: ["Any day you have Canadian income", "Any day your principal residence is in Canada", "Any calendar day you are physically inside Canadian borders", "Any day you pay Canadian taxes"],
      answer: 2,
      explanation: "Physical presence means each calendar day you are physically located within Canada's borders. Being at work, travelling within Canada, or at home all count if you are in Canada.",
    },
    {
      id: "cciq-5", chapter: "general", topic: "Application Form", difficulty: 2,
      source: "Discover Canada",
      question: "What is the main citizenship application form?",
      options: ["IMM 0008", "CIT 0002", "PR 0001", "IRCC 5444"],
      answer: 1,
      explanation: "CIT 0002 is the Application for Canadian Citizenship — Adults form. It is the primary form used by adults aged 18 and older applying for citizenship.",
    },
  ],

  "ai-citizenship-coach": [
    {
      id: "aicc-1", chapter: "general", topic: "Most Tested Topics", difficulty: 2,
      source: "Discover Canada",
      question: "Which topic area typically has the most questions on the Canadian citizenship test?",
      options: ["Canadian Geography", "Rights and Responsibilities of Citizenship", "Canadian Sports and Culture", "The History of New France"],
      answer: 1,
      explanation: "Rights and Responsibilities — including voting rights, jury duty, and the Charter — are among the most tested topics on the citizenship exam.",
    },
    {
      id: "aicc-2", chapter: "general", topic: "Study Method", difficulty: 1,
      source: "Discover Canada",
      question: "What is the most effective way to study the Discover Canada guide?",
      options: ["Read it once quickly before the test", "Study chapter by chapter, taking notes and reviewing key facts after each section", "Memorize only the dates and names", "Focus only on the government section"],
      answer: 1,
      explanation: "Studying chapter by chapter — reading, taking notes, and reviewing — is the most effective method. Use active recall (testing yourself) rather than just re-reading.",
    },
    {
      id: "aicc-3", chapter: "general", topic: "Practice Strategy", difficulty: 1,
      source: "Discover Canada",
      question: "What is the best way to practice for the citizenship test?",
      options: ["Write essays about Canadian history", "Read Canadian newspapers daily", "Answer official-style practice questions and check explanations for wrong answers", "Watch Canadian news broadcasts"],
      answer: 2,
      explanation: "Practicing with official-style multiple-choice questions (like those based on Discover Canada) and carefully reading explanations for wrong answers is the most effective preparation method.",
    },
    {
      id: "aicc-4", chapter: "general", topic: "Spaced Repetition", difficulty: 2,
      source: "Discover Canada",
      question: "How often should you review study notes to maximize retention?",
      options: ["Once a week is sufficient", "Only on the day before the test", "Daily review with spaced repetition — review at 1 day, 3 days, 7 days, and 14 days intervals", "Twice a month"],
      answer: 2,
      explanation: "Spaced repetition is the most effective study technique. Review material at increasing intervals (1 day, 3 days, 7 days, 14 days) to move information into long-term memory.",
    },
    {
      id: "aicc-5", chapter: "general", topic: "Practice Score Readiness", difficulty: 1,
      source: "Discover Canada",
      question: "If you consistently score 85%+ on practice tests, what does this suggest?",
      options: ["You should stop studying immediately", "You are likely ready for the real test but continue reviewing weak areas", "You will definitely score 100% on the real test", "You should take a harder version of the test"],
      answer: 1,
      explanation: "Consistently scoring 85%+ on practice tests suggests you are well-prepared. Continue reviewing areas where you make mistakes, as the real test may have questions worded differently.",
    },
  ],

  "citizenship-dictionary": [
    {
      id: "cd-1", chapter: "rights", topic: "Voting Rights", difficulty: 1,
      source: "Discover Canada",
      question: "What right do permanent residents in Canada NOT have that Canadian citizens do?",
      options: ["The right to work in Canada", "The right to access Medicare", "The right to vote in federal elections", "The right to public education"],
      answer: 2,
      explanation: "Permanent residents cannot vote in federal, provincial, or territorial elections. Only Canadian citizens have the right to vote in these elections.",
    },
    {
      id: "cd-2", chapter: "general", topic: "Oath of Citizenship", difficulty: 1,
      source: "Discover Canada",
      question: "In the Oath of Citizenship, to whom do new citizens pledge their loyalty?",
      options: ["The Prime Minister of Canada", "The Canadian people", "The Monarch of Canada (King/Queen)", "The Governor General"],
      answer: 2,
      explanation: "In the Oath, new citizens swear or affirm loyalty to 'His/Her Majesty the King/Queen' — the Monarch of Canada — and promise to follow Canadian laws.",
    },
    {
      id: "cd-3", chapter: "general", topic: "Citizenship Certificate", difficulty: 1,
      source: "Discover Canada",
      question: "What official document do new citizens receive at the end of the citizenship ceremony?",
      options: ["A Canadian passport", "A Permanent Resident Card", "A Citizenship Certificate", "A Social Insurance Card"],
      answer: 2,
      explanation: "At the citizenship ceremony, after taking the Oath, new citizens receive their Citizenship Certificate — the official proof of Canadian citizenship.",
    },
    {
      id: "cd-4", chapter: "rights", topic: "Charter Year", difficulty: 1,
      source: "Discover Canada",
      question: "In what year was the Canadian Charter of Rights and Freedoms added to the Constitution?",
      options: ["1867", "1960", "1982", "1988"],
      answer: 2,
      explanation: "The Charter became part of Canada's Constitution through the Constitution Act, 1982, when Canada patriated its Constitution from the United Kingdom.",
    },
    {
      id: "cd-5", chapter: "government", topic: "Governor General Appointment", difficulty: 2,
      source: "Discover Canada",
      question: "Who appoints Canada's Governor General?",
      options: ["The Senate", "The Prime Minister directly", "The Monarch on the advice of the Prime Minister", "The Chief Justice of the Supreme Court"],
      answer: 2,
      explanation: "The Governor General is formally appointed by the Monarch (King or Queen), but only on the advice of the Prime Minister. In practice, the PM recommends a candidate.",
    },
  ],

  "citizenship-faq": [
    {
      id: "cfaq-1", chapter: "general", topic: "Physical Presence Exception", difficulty: 2,
      source: "Discover Canada",
      question: "Can someone apply for Canadian citizenship before completing 3 years of physical presence?",
      options: ["Yes, with a special exemption", "Yes, if they have a job offer", "No — they must have at least 1,095 days of physical presence in the past 5 years", "Yes, if married to a Canadian citizen"],
      answer: 2,
      explanation: "No exceptions are made to the physical presence requirement. You must have been physically present in Canada for at least 1,095 days within the 5 years before your application.",
    },
    {
      id: "cfaq-2", chapter: "general", topic: "Children and Test", difficulty: 1,
      source: "Discover Canada",
      question: "Do children under 18 need to take the Canadian citizenship test?",
      options: ["Yes, all applicants must take the test", "No — applicants under 18 are exempt from the knowledge test", "Only children 14 and older must take it", "Children over 12 must take a simplified test"],
      answer: 1,
      explanation: "Children under 18 years of age are exempt from the citizenship knowledge test and the language requirement. They can be included in a parent's application.",
    },
    {
      id: "cfaq-3", chapter: "general", topic: "Dual Citizenship", difficulty: 1,
      source: "Discover Canada",
      question: "Does Canada allow citizens to hold citizenship in another country at the same time?",
      options: ["No — you must renounce all other citizenships", "Yes — Canada permits dual or multiple citizenship", "Only if the other country allows it", "Only for Commonwealth countries"],
      answer: 1,
      explanation: "Canada permits dual and multiple citizenship. You are not required to give up your original citizenship when you become a Canadian citizen.",
    },
    {
      id: "cfaq-4", chapter: "general", topic: "Application Fee", difficulty: 2,
      source: "Discover Canada",
      question: "What is the approximate government processing fee for an adult citizenship application?",
      options: ["$100 CAD", "$350 CAD", "$630 CAD", "$1,200 CAD"],
      answer: 2,
      explanation: "The government fee for an adult citizenship application is $630 CAD (including the $100 right of citizenship fee and $530 processing fee), as of the most recent fee schedule.",
    },
    {
      id: "cfaq-5", chapter: "general", topic: "Processing Time", difficulty: 2,
      source: "Discover Canada",
      question: "How long does it typically take for IRCC to process a citizenship application?",
      options: ["3–6 months", "6–12 months", "12–24 months", "3–5 years"],
      answer: 2,
      explanation: "Processing times vary, but IRCC typically takes 12–24 months to process a citizenship application, depending on application volumes and the completeness of your file.",
    },
  ],
};
